apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lvms-vmstorage-immediate
provisioner: topolvm.io
parameters:
  csi.storage.k8s.io/fstype: xfs
  topolvm.io/device-class: vmstorage
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
