apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu2404-gpu-vm
  namespace: gpu-vms
  labels:
    app: ubuntu2404-gpu-vm
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: ubuntu2404-gpu-vm-disk
    spec:
      source:
        http:
          url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
      storage:
        resources:
          requests:
            storage: 80Gi
        storageClassName: lvms-vmstorage-immediate
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu2404-gpu-vm
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 64
          sockets: 1
          threads: 1
        machine:
          type: q35
        memory:
          guest: 400Gi
        resources:
          requests:
            memory: 400Gi
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinit
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          hostDevices:
          - name: gpu-0
            deviceName: nvidia.com/gpu
          - name: gpu-1
            deviceName: nvidia.com/gpu
          - name: gpu-2
            deviceName: nvidia.com/gpu
          - name: gpu-3
            deviceName: nvidia.com/gpu
          - name: gpu-4
            deviceName: nvidia.com/gpu
          - name: gpu-5
            deviceName: nvidia.com/gpu
          - name: gpu-6
            deviceName: nvidia.com/gpu
          - name: gpu-7
            deviceName: nvidia.com/gpu
          - name: nvswitch-0
            deviceName: nvidia.com/nvswitch
          - name: nvswitch-1
            deviceName: nvidia.com/nvswitch
          - name: nvswitch-2
            deviceName: nvidia.com/nvswitch
          - name: nvswitch-3
            deviceName: nvidia.com/nvswitch
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        dataVolume:
          name: ubuntu2404-gpu-vm-disk
      - name: cloudinit
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: ubuntu
            password: ubuntu123
            chpasswd:
              expire: false
            ssh_pwauth: true
            ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBU7aW/KKovroBJp5IBsJj4PhixblQ+bwo8nUnpWMt+ZEvW5p6AY1Gv5sbyfvvL1iHIucxt/9F9gp0MDdBzjVyX3OJc2Ktm60mLOIFC9FajCwzEkodaZtl+5dIjwTOLLlLQFZAVNvMlog9oFK2qNwnSwbnXCj8W23ciMrKiOI3wVecwLEhdP/NE5wwv/lU7UccsjFc7rlwg3q0rSHwL86pgPUERWxu7vSfE0lgLKwMM1G82Cqq/hbtO/AFW2s3czVZPee67TT0v2KkZBQnr2uy24uV3E77GVDaRkI/Fa90JJP4ryKqytkO2chaJ8B9EzvbigCDkMUkMCrFjTYwLaMdewnubFXyzJl2FI6G/CN8Qkq7Do7B2GVRCGfwavVO6Ei6TTCwfOqj9HnozhWL+XMgDtI/YmFHmwWqSDwB333UHJrTVuv4xjc4x8pUI+8G4RMay1crCXi1CsDg3T+V2kPsXMb7pH/N6+5wRTridhFCSCycrdR93zoN7VVTdOoe9PoTDqWPZaLtiNLo5U5s1mSBKPCKq+cralw3ojsod/7qaEwf9vFk/jkIQt+Q2n51ctoZLzpTcUBTwu23l6UCFo+PK783WETHyLO6+5Wu+5E1Fffy4U9fJlkvn0IzTmJd1cm9swCa/4UrO3X62Ic3plUhHxAVXQ3EnOo+rvq0/JmZKw== nvidia@lp-nvaie-rh-gpu01
